# Give a name to the eureka server
spring:
  application:
    name: eureka-server

# HTTP Server (Tomcat) port
server:
  port: 8761 # default port for eureka server

# Configure this Discovery Server
eureka:
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
