spring:
  application:
    name: eureka-server # Identifier of this application

server:
  port: 8761 # default port for eureka server

eureka:
  client:  
    responseCacheUpdateInvervalMs: 5
    registerWithEureka: false
    fetchRegistry: false
    # We don't need it since the eureka server is obviously not a client.
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of the eureka server for registration